### ISSUE TITLE
[Feature]: Auto create GitHub bug issue when system breaks

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-api#117]
### Description of feature request

It would be great to auto create an bug issue on GitHub when the system is on production and breaks in the code with all traceback.

### Why is this needed

Save a lot of time checking in logs on the server etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mjovanc** [comment]
This should only be for the official Hugin Cache if we decide to implement this.

**Comment by mjovanc** [comment]
@Coffeboi I put this issue on you, I think it would be interesting to work on. I don't have a clear picture what needs to be done exactly. But a thought is that we should look where the system crashes and then send a POST request using GitHub API to create a new issue tied to this repo.

**Comment by Coffeboi** [comment]
@mjovanc sounds like fun, i will look into it.
