### ISSUE TITLE
Change name to hugin-api?

### ISSUE THREAD

**Issue by f-r00t** [kryptokrona/hugin-api#194]
My motivation comes from when (and if) we decide to enable message _sending_ from the hugin cache, "hugin-api" makes a whole lot more sense than "hugin-cache".

What do you guys think?

**Comment by mjovanc** [comment]
That was my first initial thought when I started building it. I'm all for it.

**Comment by mjovanc** [comment]
But if we use it as message sending, I might want to re-design the whole thing. As I started doing before with Spring Boot since that's currently my expertise in building APIs. Works?

**Comment by f-r00t** [comment]
I trust in your judgement! Let's go for hugin-api at least!

**Comment by TechyGuy17** [comment]
Sounds fair!

**Comment by mjovanc** [comment]
I Will make this my priority. Its a very important API and it deserves a good care and development 😎

**Comment by mjovanc** [comment]
Changed the project name on most places. Still there is a lot of small things to fix. But however it's done for the most part! I will close this issue since this will be an on-going work.
