### ISSUE TITLE
Send alerts to Hugin group when CPU/RAM/DISK is exceeding 80%

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-api#245]
Perhaps we need to extract the data from Prometheus for this.

**Comment by mjovanc** [comment]
Changing this to send alerts to a group on Hugin instead.

**Comment by TechyGuy17** [comment]
Im on it

**Comment by mjovanc** [comment]
We should have a variable in provision_vps.yml that we can set to a specific hash of a group so the user who deploys the API can decide to what group the alerts should go to. And in the charts JS we should set this from Ansible.
